### ISSUE TITLE
Activity with no grade yet in the course view (student)

### ISSUE THREAD

**Issue by marcinz99** [upel-dev/upel3.0#70]
![Screenshot_2021-05-26 UPeL3 0](https://user-images.githubusercontent.com/44765764/119881424-9342e380-bf2d-11eb-9f65-48ef85fc51a9.png)

Steps to reproduce:
* create new activity and do not give grades yet
* log in as a student and head to the course view

**Comment by Krlstch** [comment]
Fixed in PR #72.
